version: '3.2'

volumes:
  db-data:
  tmp-data:
  redis-data:

services:
  app:
    build:
      dockerfile: cmd/crud/Dockerfile
      context: ./
    restart: on-failure
    env_file:
      - cmd/crud/.env
    depends_on:
      - consul
      - postgres
    networks:
      - big_net

  postgres:
    image: postgres:14.4
    restart: on-failure
    environment:
      - POSTGRES_USER=gorm
      - POSTGRES_PASSWORD=gorm
      - POSTGRES_DB=gorm
    volumes:
      - ./dump:/docker-entrypoint-initdb.d/
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - big_net

  nginx:
    build:
      dockerfile: nginx/Dockerfile
      context: ./
    ports:
      - "8080:80"
    networks:
      - big_net
    depends_on:
      - app
    restart: on-failure

  consul:
    image: consul:latest
    ports:
      - "8500:8500"
    networks:
      - big_net

networks:
  big_net:
    driver: bridge