version: '3.2'

volumes:
  db-data:
  tmp-data:
  redis-data:

services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: ./
    restart: on-failure
    ports:
      - "8888:3000"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:14.4
    restart: on-failure
    environment:
      - POSTGRES_USER=gorm
      - POSTGRES_PASSWORD=gorm
      - POSTGRES_DB=gorm
    volumes:
      - ./dump:/docker-entrypoint-initdb.d/
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
